E0 <- url('http://www.football-data.co.uk/mmz4281/2021/E0.csv')
E1 <- url('http://www.football-data.co.uk/mmz4281/2021/E1.csv')
E2 <- url('http://www.football-data.co.uk/mmz4281/2021/E0.csv')
E3 <- url('http://www.football-data.co.uk/mmz4281/2021/E1.csv')
EC <- url('http://www.football-data.co.uk/mmz4281/2021/E0.csv')

epl <- read.csv(E0)
championship <- read.csv(E1)
league1 <- read.csv(E2)
league2 <- read.csv(E3)
national_league <- read.csv(EC)
data <- rbind(epl,championship)
View(data)
str(data)
library('lubridate')
data$Date <- dmy(data$Date)
allteams21 <- data[order(as.Date(data$Date, format = "%d/%m/%Y"), decreasing = FALSE),]
latest_10 <- subset(allteams21, Date <= max(Date))
nrow(latest_10)
View(latest_10)
