#Master file to run all other scripts
#load the data
source("divisions.R")
source("GoalTotalsV2.R")
source("GSmatrix.R")
source("GCmatrix.R")
source("WinMargin.R")
source("YCmatrix.R")
source("RCmatrix.R")
source("RedTotalsV2.R")
source("YellowtotalsV2.R")
source("Teamform.R")
source("CSform.R")
source("TGmatrix.R")
source("Totalgoals.R")
source("TeamAgainst.R")
source("ShotsAnalysis.R")
source("LeagueTables.R")
source("PoissonModel.R")
unlink("Divisions/*",recursive = T,force = T)
source("Matchday.R")
source("KROUNDS.R")
source("GSmatrix_rounds.R")
source("GCmatrix_rounds.R")
source("TGmatrix_rounds.R")
source("Teamform_rounds.R")
source("Winmargin_rounds.R")
source("RejoinMatrix.R")
source("MasterWrite.R")
source("RoundMatrix.R")
source("LastSix.R")
source("LeagueFixtures.R")
source("TableSimulation.R")

