library('dplyr')
library('janitor')
Sys.setenv(JAVA_HOME ="C:\\Program Files\\Java\\jre1.8.0_281")
library('xlsx')
library('scales')
#B1
write.xlsx(points_b1,'Divisions/B1.xlsx', sheetName = "Table")
write.xlsx(b1_formmatrix,'Divisions/B1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(b1_goalscoredmatrix,'Divisions/B1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(b1_goalconcededmatrix,'Divisions/B1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(b1_goaltotalmatrix,'Divisions/B1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(b1_winmarginmatrix,'Divisions/B1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(b1_goaltotalsv2,'Divisions/B1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(b1_yellowtotalsv2,'Divisions/B1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(b1_redtotalsv2,'Divisions/B1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(b1_ovundata,'Divisions/B1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(b1_shots_analysis,'Divisions/B1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#D1
write.xlsx(points_d1,'Divisions/D1.xlsx', sheetName = "Table")
write.xlsx(d1_formmatrix,'Divisions/D1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(d1_goalscoredmatrix,'Divisions/D1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(d1_goalconcededmatrix,'Divisions/D1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(d1_goaltotalmatrix,'Divisions/D1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(d1_goaltotalsv2,'Divisions/D1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(d1_winmarginmatrix,'Divisions/D1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(d1_yellowtotalsv2,'Divisions/D1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(d1_redtotalsv2,'Divisions/D1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(d1_ovundata,'Divisions/D1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(d1_shots_analysis,'Divisions/D1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#D2
write.xlsx(points_d2,'Divisions/D2.xlsx', sheetName = "Table")
write.xlsx(d2_formmatrix,'Divisions/D2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(d2_goalscoredmatrix,'Divisions/D2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(d2_goalconcededmatrix,'Divisions/D2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(d2_goaltotalmatrix,'Divisions/D2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(d2_winmarginmatrix,'DivisionsD2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(d2_goaltotalsv2,'Divisions/D2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(d2_yellowtotalsv2,'Divisions/D2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(d2_redtotalsv2,'Divisions/D2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(d2_ovundata,'Divisions/D2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(d2_shots_analysis,'Divisions/D2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#E0
write.xlsx(points_e0,'Divisions/E0.xlsx', sheetName = "Table")
write.xlsx(e0_formmatrix,'Divisions/E0.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(e0_goalscoredmatrix,'Divisions/E0.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(e0_goalconcededmatrix,'Divisions/E0.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(e0_winmarginmatrix,'Divisions/E0.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(e0_goaltotalmatrix,'Divisions/E0.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(e0_goaltotalsv2,'Divisions/E0.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(e0_yellowtotalsv2,'Divisions/E0.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(e0_redtotalsv2,'Divisions/E0.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(e0_ovundata,'Divisions/E0.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(e0_shots_analysis,'Divisions/E0.xlsx', sheetName = "Shots Analysis", append = TRUE)
#E1
write.xlsx(points_e1,'Divisions/E1.xlsx', sheetName = "Table")
write.xlsx(e1_formmatrix,'Divisions/E1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(e1_goalscoredmatrix,'Divisions/E1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(e1_goalconcededmatrix,'Divisions/E1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(e1_winmarginmatrix,'Divisions/E1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(e1_goaltotalmatrix,'Divisions/E1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(e1_goaltotalsv2,'Divisions/E1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(e1_yellowtotalsv2,'Divisions/E1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(e1_redtotalsv2,'Divisions/E1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(e1_ovundata,'Divisions/E1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(e1_shots_analysis,'Divisions/E1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#E2
write.xlsx(points_e2,'Divisions/E2.xlsx', sheetName = "Table")
write.xlsx(e2_formmatrix,'Divisions/E2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(e2_goalscoredmatrix,'Divisions/E2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(e2_goalconcededmatrix,'Divisions/E2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(e2_winmarginmatrix,'Divisions/E2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(e2_goaltotalmatrix,'Divisions/E2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(e2_goaltotalsv2,'Divisions/E2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(e2_yellowtotalsv2,'Divisions/E2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(e2_redtotalsv2,'Divisions/E2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(e2_ovundata,'Divisions/E2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(e2_shots_analysis,'Divisions/E2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#E3
write.xlsx(points_e3,'Divisions/E3.xlsx', sheetName = "Table")
write.xlsx(e3_formmatrix,'Divisions/E3.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(e3_goalscoredmatrix,'Divisions/E3.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(e3_goalconcededmatrix,'Divisions/E3.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(e3_winmarginmatrix,'Divisions/E3.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(e3_goaltotalmatrix,'Divisions/E3.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(e3_goaltotalsv2,'Divisions/E3.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(e3_yellowtotalsv2,'Divisions/E3.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(e3_redtotalsv2,'Divisions/E3.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(e3_ovundata,'Divisions/E3.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(e3_shots_analysis,'Divisions/E3.xlsx', sheetName = "Shots Analysis", append = TRUE)
#EC
write.xlsx(points_ec,'Divisions/EC.xlsx', sheetName = "Table")
write.xlsx(ec_form_h,'Divisions/EC.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(ec_goalscored_h,'Divisions/EC.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(ec_goalconceded_h,'Divisions/EC.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(ec_winmarginmatrix,'Divisions/EC.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(ec_totalgoals_h,'Divisions/EC.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(ec_goaltotalsv2,'Divisions/EC.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(ec_yellowtotalsv2,'Divisions/EC.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(ec_redtotalsv2,'Divisions/EC.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(ec_ovundata,'Divisions/EC.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(ec_shots_analysis,'Divisions/EC.xlsx', sheetName = "Shots Analysis", append = TRUE)
#F1
write.xlsx(points_f1,'Divisions/F1.xlsx', sheetName = "Table")
write.xlsx(f1_formmatrix,'Divisions/F1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(f1_goalscoredmatrix,'Divisions/F1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(f1_goalconcededmatrix,'Divisions/F1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(f1_winmarginmatrix,'Divisions/F1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(f1_goaltotalmatrix,'Divisions/F1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(f1_goaltotalsv2,'Divisions/F1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(f1_yellowtotalsv2,'Divisions/F1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(f1_redtotalsv2,'Divisions/F1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(f1_ovundata,'Divisions/F1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(f1_shots_analysis,'Divisions/F1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#F2
write.xlsx(points_f2,'Divisions/F2.xlsx', sheetName = "Table")
write.xlsx(f2_formmatrix,'Divisions/F2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(f2_goalscoredmatrix,'Divisions/F2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(f2_goalconcededmatrix,'Divisions/F2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(f2_winmarginmatrix,'Divisions/F2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(f2_goaltotalmatrix,'Divisions/F2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(f2_goaltotalsv2,'Divisions/F2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(f2_yellowtotalsv2,'Divisions/F2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(f2_redtotalsv2,'Divisions/F2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(f2_ovundata,'Divisions/F2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(f2_shots_analysis,'Divisions/F2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#G1
write.xlsx(points_g1,'Divisions/G1.xlsx', sheetName = "Table")
write.xlsx(g1_formmatrix,'Divisions/G1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(g1_goalscoredmatrix,'Divisions/G1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(g1_goalconcededmatrix,'Divisions/G1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(g1_winmarginmatrix,'Divisions/G1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(g1_goaltotalmatrix,'Divisions/G1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(g1_goaltotalsv2,'Divisions/G1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(g1_yellowtotalsv2,'Divisions/G1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(g1_redtotalsv2,'Divisions/G1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(g1_ovundata,'Divisions/G1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(g1_shots_analysis,'Divisions/G1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#I1
write.xlsx(points_i1,'Divisions/I1.xlsx', sheetName = "Table")
write.xlsx(i1_formmatrix,'Divisions/I1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(i1_goalscoredmatrix,'Divisions/I1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(i1_goalconcededmatrix,'Divisions/I1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(i1_winmarginmatrix,'Divisions/I1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(i1_goaltotalmatrix,'Divisions/I1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(i1_goaltotalsv2,'Divisions/I1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(i1_yellowtotalsv2,'Divisions/I1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(i1_redtotalsv2,'Divisions/I1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(i1_ovundata,'Divisions/I1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(i1_shots_analysis,'Divisions/I1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#I2
write.xlsx(points_i2,'Divisions/I2.xlsx', sheetName = "Table")
write.xlsx(i2_formmatrix,'Divisions/I2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(i2_goalscoredmatrix,'Divisions/I2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(i2_goalconcededmatrix,'Divisions/I2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(i2_winmarginmatrix,'Divisions/I2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(i2_goaltotalmatrix,'Divisions/I2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(i2_goaltotalsv2,'Divisions/I2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(i2_yellowtotalsv2,'Divisions/I2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(i2_redtotalsv2,'Divisions/I2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(i2_ovundata,'Divisions/I2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(i2_shots_analysis,'Divisions/I2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#N1
write.xlsx(points_n1,'Divisions/N1.xlsx', sheetName = "Table")
write.xlsx(n1_formmatrix,'Divisions/N1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(n1_goalscoredmatrix,'Divisions/N1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(n1_goalconcededmatrix,'Divisions/N1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(n1_winmarginmatrix,'Divisions/N1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(n1_goaltotalmatrix,'Divisions/N1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(n1_goaltotalsv2,'Divisions/N1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(n1_yellowtotalsv2,'Divisions/N1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(n1_redscored_h,'Divisions/N1.xlsx', sheetName = "Red Cards", append = TRUE)
write.xlsx(n1_ovundata,'Divisions/N1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(n1_shots_analysis,'Divisions/N1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#P1
write.xlsx(points_p1,'Divisions/P1.xlsx', sheetName = "Table")
write.xlsx(p1_formmatrix,'Divisions/P1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(p1_goalscoredmatrix,'Divisions/P1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(p1_goalconcededmatrix,'Divisions/P1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(p1_winmarginmatrix,'Divisions/P1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(p1_goaltotalmatrix,'Divisions/P1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(p1_goaltotalsv2,'Divisions/P1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(p1_yellowtotalsv2,'Divisions/P1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(p1_redtotalsv2,'Divisions/P1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(p1_ovundata,'Divisions/P1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(p1_shots_analysis,'Divisions/P1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SC0
write.xlsx(points_sc0,'Divisions/SC0.xlsx', sheetName = "Table")
write.xlsx(sc0_formmatrix,'Divisions/SC0.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sc0_goalscoredmatrix,'Divisions/SC0.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sc0_goalconcededmatrix,'Divisions/SC0.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sc0_winmarginmatrix,'Divisions/SC0.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sc0_goaltotalmatrix,'Divisions/SC0.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sc0_goaltotalsv2,'Divisions/SC0.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sc0_yellowtotalsv2,'Divisions/SC0.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sc0_redtotalsv2,'Divisions/SC0.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(sc0_ovundata,'Divisions/SC0.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sc0_shots_analysis,'Divisions/SC0.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SC1
write.xlsx(points_sc1,'Divisions/SC1.xlsx', sheetName = "Table")
write.xlsx(sc1_formmatrix,'Divisions/SC1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sc1_goalscoredmatrix,'Divisions/SC1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sc1_goalconcededmatrix,'Divisions/SC1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sc1_winmarginmatrix,'Divisions/SC1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sc1_goaltotalmatrix,'Divisions/SC1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sc1_goaltotalsv2,'Divisions/SC1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sc1_yellowtotalsv2,'Divisions/SC1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sc1_redtotalsv2,'Divisions/SC1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(sc1_ovundata,'Divisions/SC1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sc1_shots_analysis,'Divisions/SC1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SC2
write.xlsx(points_sc2,'Divisions/SC2.xlsx', sheetName = "Table")
write.xlsx(sc2_formmatrix,'Divisions/SC2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sc2_goalscoredmatrix,'Divisions/SC2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sc2_goalconcededmatrix,'Divisions/SC2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sc2_winmarginmatrix,'Divisions/SC2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sc2_goaltotalmatrix,'Divisions/SC2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sc2_goaltotalsv2,'Divisions/SC2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sc2_yellowtotalsv2,'Divisions/SC2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sc2_redtotalsv2,'Divisions/SC2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(sc2_ovundata,'Divisions/SC2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sc2_shots_analysis,'Divisions/SC2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SC3
write.xlsx(points_sc3,'Divisions/SC3.xlsx', sheetName = "Table")
write.xlsx(sc3_formmatrix,'Divisions/SC3.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sc3_goalscoredmatrix,'Divisions/SC3.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sc3_goalconcededmatrix,'Divisions/SC3.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sc3_winmarginmatrix,'Divisions/SC3.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sc3_goaltotalmatrix,'Divisions/SC3.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sc3_goaltotalsv2,'Divisions/SC3.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sc3_yellowtotalsv2,'Divisions/SC3.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sc3_redtotalsv2,'Divisions/SC3.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(sc3_ovundata,'Divisions/SC3.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sc3_shots_analysis,'Divisions/SC3.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SP1
write.xlsx(points_sp1,'Divisions/SP1.xlsx', sheetName = "Table")
write.xlsx(sp1_formmatrix,'Divisions/SP1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sp1_goalscoredmatrix,'Divisions/SP1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sp1_goalconcededmatrix,'Divisions/SP1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sp1_winmarginmatrix,'Divisions/SP1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sp1_goaltotalmatrix,'Divisions/SP1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sp1_goaltotalsv2,'Divisions/SP1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sp1_yellowtotalsv2,'Divisions/SP1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sp1_redscored_h,'Divisions/SP1.xlsx', sheetName = "Red Cards", append = TRUE)
write.xlsx(sp1_ovundata,'Divisions/SP1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sp1_shots_analysis,'Divisions/SP1.xlsx', sheetName = "Shots Analysis", append = TRUE)
#SP2
write.xlsx(points_sp2,'Divisions/SP2.xlsx', sheetName = "Table")
write.xlsx(sp2_formmatrix,'Divisions/SP2.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(sp2_goalscoredmatrix,'Divisions/SP2.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(sp2_goalconcededmatrix,'Divisions/SP2.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(sp2_winmarginmatrix,'Divisions/SP2.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(sp2_goaltotalmatrix,'Divisions/SP2.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(sp2_goaltotalsv2,'Divisions/SP2.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(sp2_yellowtotalsv2,'Divisions/SP2.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(sp2_redtotalsv2,'Divisions/SP2.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(sp2_ovundata,'Divisions/SP2.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(sp2_shots_analysis,'Divisions/SP2.xlsx', sheetName = "Shots Analysis", append = TRUE)
#T1
write.xlsx(points_t1,'Divisions/T1.xlsx', sheetName = "Table")
write.xlsx(t1_formmatrix,'Divisions/T1.xlsx', sheetName = "Form", append = TRUE)
write.xlsx(t1_goalscoredmatrix,'Divisions/T1.xlsx', sheetName = "Goals scored", append = TRUE)
write.xlsx(t1_goalconcededmatrix,'Divisions/T1.xlsx', sheetName = "Goals conceded", append = TRUE)
write.xlsx(t1_winmarginmatrix,'Divisions/T1.xlsx', sheetName = "Winmargin", append = TRUE)
write.xlsx(t1_goaltotalmatrix,'Divisions/T1.xlsx', sheetName = "Total Goals form", append = TRUE)
write.xlsx(t1_goaltotalsv2,'Divisions/T1.xlsx', sheetName = "Goal totals v2", append = TRUE)
write.xlsx(t1_yellowtotalsv2,'Divisions/T1.xlsx', sheetName = "Yellow Totals", append = TRUE)
write.xlsx(t1_redtotalsv2,'Divisions/T1.xlsx', sheetName = "Red Totals", append = TRUE)
write.xlsx(t1_ovundata,'Divisions/T1.xlsx', sheetName = "OVUN", append = TRUE)
write.xlsx(t1_shots_analysis,'Divisions/T1.xlsx', sheetName = "Shots Analysis", append = TRUE)
