library('plyr')
library('dplyr')
library('janitor')
Sys.setenv(JAVA_HOME ="C:\\Program Files\\Java\\jre1.8.0_281")
library('xlsx')
library('scales')
library('lubridate')
library('sqldf')
library('mgsub')
###########
source("ARG.R")
source("AUT.R")
source("BRAZIL.R")
source("CHN.R")
source("DNK.R")
source("FIN.R")
source("IRL.R")
source("JPN.R")
source("MEX.R")
source("MLS.R")
source("NOR.R")
source("POL.R")
source("ROU.R")
source("RUS.R")
source("SWE.R")
#####################
R_home_newleagues <- rbind(arg_home_poisson,aut_home_poisson,bra_home_poisson,chn_home_poisson,dnk_home_poisson,fin_home_poisson,irl_home_poisson,jpn_home_poisson,mex_home_poisson,nor_home_poisson,pol_home_poisson,rou_home_poisson,rus_home_poisson,swe_home_poisson,mls_home_poisson)
R_away_newleagues <- rbind(arg_away_poisson,aut_away_poisson,bra_away_poisson,chn_away_poisson,dnk_away_poisson,fin_away_poisson,irl_away_poisson,jpn_away_poisson,mex_away_poisson,nor_away_poisson,pol_away_poisson,rou_away_poisson,rus_away_poisson,swe_away_poisson,mls_away_poisson)

unlink('R_home_newleagues.csv')
unlink('R_away_newleagues.csv')

R_home_newleagues <- mgsub(R_home_newleagues,c("ARG","AUT","BRA","CHN","DNK","FIN","IRL","JPN","MEX","NOR","POL","ROU","RUS","SWE"),c("Liga Profesional","Admiral Bundesliga","Serie A","Super League","Superliga","Veikkausliiga","Premier Division","J1 League","Liga MX","Eliteserien","Ekstraklasa","Liga 1","Premier League","Allsvenskan"))
R_away_newleagues <- mgsub(R_away_newleagues,c("ARG","AUT","BRA","CHN","DNK","FIN","IRL","JPN","MEX","NOR","POL","ROU","RUS","SWE"),c("Liga Profesional","Admiral Bundesliga","Serie A","Super League","Superliga","Veikkausliiga","Premier Division","J1 League","Liga MX","Eliteserien","Ekstraklasa","Liga 1","Premier League","Allsvenskan"))

write.csv(R_home_newleagues,'R_home_newleagues.csv')
write.csv(R_away_newleagues,'R_away_newleagues.csv')
