data <- read.csv('allteams2010-present.csv')
#create total_goals column
total_goals <- data$FTHG + data$FTAG
#assign column to data frame
data <- cbind(data,total_goals)
colnames(data)
data$OV25 <- ifelse(data$total_goals >= 3,"Y","N")
colnames(data)
library('dplyr')
summary_div <- data %>% group_by(Div) %>% summarise_if(is.numeric,sum)
summary_div
summary_mean <- data %>% group_by(Div) %>% summarise_all(mean)
write.csv(summary_mean,"meansummary.csv")
#nrow(newdata[newdata$Div == "E0",])
write.csv(summary_div,"2010psumall.csv")
divisions <- unique(newdata$Div)
index <- seq(1,22)
install.packages('janitor')
library('janitor')
ov25dist <- tabyl(data,Div,OV25) %>% adorn_percentages("row") %>% adorn_pct_formatting(digits = 1)
ov25dist
write.csv(ov25dist,'ov25all.csv')
current_season <- read.csv('allteams20202021SOT.csv')
current_season$total_goals <- current_season$FTHG + current_season$FTAG
current_season$OV25 <- ifelse(current_season$total_goals >= 3,"Y","N")
head(current_season)
ov25current_season <- tabyl(current_season,Div,OV25) %>% adorn_percentages("row") %>% adorn_pct_formatting(digits = 1)
write.csv(ov25current_season,'curren_season0v25.csv')
hdacurrent_season <- tabyl(current_season,Div,FTR) %>% adorn_percentages("row") %>% adorn_pct_formatting(digits = 1)
write.csv(hdacurrent_season,'hda.csv')
hgscored <- aggregate(current_season$FTHG,by = list(HomeTeam = current_season$HomeTeam),FUN=sum)
agscored <- aggregate(current_season$FTAG,by = list(AwayTeam = current_season$AwayTeam),FUN=sum)
hgconceded <- aggregate(current_season$FTAG,by = list(HomeTeam = current_season$HomeTeam),FUN=sum)
agconceded <- aggregate(current_season$FTHG,by = list(AwayTeam = current_season$AwayTeam),FUN=sum)
eredivisie <- subset(current_season, Div == "N1")
transposed <- as.data.frame(t(eredivisie))
teams <- unique(eredivisie['HomeTeam'])
